import java.util.ArrayList;
import java.util.HashSet;
import java.util.TreeSet;

public class EntrySets {

	public static void main(String[] args) {

		ArrayList<Entry<String>> list = new ArrayList<>();

		list.add(new Entry(10, "A"));
		list.add(new Entry(50, "B"));
		list.add(new Entry(30, "C"));
		list.add(new Entry(10, "A"));
		list.add(new Entry(50, "B"));
		
		System.out.println("The entries are: " + list);
		
		HashSet<Entry<String>> hset = new HashSet<>();
		TreeSet<Entry<String>> tset = new TreeSet<>();	

		
		// Question 1:
		
		hset.addAll(list);
		System.out.println("The hashSet is: " + hset);
		// currently displays [A=10, C=30, A=10, B=50, B=50]
		// edit Entry.java so that the hashSet correctly filters out the repeated items and only keeps 3 of these items							
		
		
		// Question 2:
		
		tset.addAll(list);
		System.out.println("The treeSet is: " + tset);
		// currently causes an error
		// edit Entry.java so that the treeSet correctly stores 3 items in order sorted by their key value							
		
		// DO NOT EDIT THIS FILE. EDIT ONLY THE Entry.java FILE

	}

}
